# Generated by Django 5.0.6 on 2024-07-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
