# Generated by Django 5.0.6 on 2024-07-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_container_id_alter_project_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('Python', 'Python')], default='Python', max_length=10),
            preserve_default=False,
        ),
    ]
