# Generated by Django 5.0.6 on 2024-07-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_server_port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
